on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(git describe --tags) >> ${GITHUB_ENV}
      - name: Set GIT_COMMIT env
        run: echo GIT_COMMIT=$(git rev-list -1 HEAD) >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1.14
        with:
          binary_name: migrate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz"
          ldflags: -X "github.com/SvcManager/svcat-operator-migrator/cmd.GitCommit=${{ env.GIT_COMMIT }}" -X "github.com/SvcManager/svcat-operator-migrator/cmd.Version=${{ env.APP_VERSION }}"